---
- name: Download baked agent
  ansible.builtin.uri:
    url: "{{ api_url }}/domain-types/agent/actions/download_by_host/invoke?host_name={{ inventory_hostname }}&os_type=linux_rpm&agent_type=host_name"
    dest: "/tmp/check-mk-agent-{{ inventory_hostname }}.rpm"
    method: GET
    headers:
      Authorization: "Bearer automation {{ cmk_automation_pw }}"
      Accept: "application/octet-stream"

- name: Update baked agent
  ansible.buitlin.package:
    name:
      - "/tmp/check-mk-agent-{{ inventory_hostname }}.rpm"
    state: latest
    disable_gpg_check: true

- name: Remove downloaded files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/check-mk-agent-{{ inventory_hostname }}.rpm"
