---
- name: Install python packages
  ansible.builtin.package:
    name:
      - python39-pyyaml
      - python39-requests
    state: present

- name: Install Python modules
  ansible.builtin.pip:
    name:
      - robotframework
      - robotframework-requests
      - robotframework-soaplibrary
      - Authlib
      - mergedeep
      - python-dateutil
    state: present
    executable: /usr/bin/pip3
  environment:
    https_proxy: "{{ https_proxy }}"
