---
- name: Run CheckMK plugin installation
  include_role:
    name: cmk-utils
    tasks_from: install_mkp.yml
  vars:
    name: robotmk
    url: "{{ robotmk_download_url }}"

- name: Ensure robot directory exists
  ansible.builtin.file:
    path: /usr/lib/check_mk_agent/robot
    state: directory
    mode: '0755'

- name: Deploy Test suites
  ansible.posix.synchronize:
    src: "robot/{{ item }}"
    dest: "/usr/lib/check_mk_agent/robot/"
    mode: push
  loop: "{{ robotmk_suites }}"

- name: Create RobotMK agent rule
  tribe29.checkmk.rule:
    server_url: "{{ cmk_server_url }}"
    site: "{{ cmk_site_name }}"
    automation_user: "automation"
    automation_secret: "{{ cmk_automation_pw }}"
    ruleset: "agent_config:robotmk"
    rule:
      properties:
        comment: "Managed by ansible"
        description: "Deploy RobotMK agent on cmk server"
        disabled: false
      conditions:
        host_tags: []
        service_labels: []
        host_labels:
          - key: "cmk/check_mk_server"
            operator: "is"
            value: "yes"
      value_raw: "{{ lookup('ansible.builtin.template', 'agent_rule.j2') | string }}"
    state: present

- name: Create RobotMK inventory rule
  tribe29.checkmk.rule:
    server_url: "{{ cmk_server_url }}"
    site: "{{ cmk_site_name }}"
    automation_user: "automation"
    automation_secret: "{{ cmk_automation_pw }}"
    ruleset: "inventory_robotmk_rules"
    rule:
      properties:
        comment: "Managed by ansible"
        description: "RobotMK services inventory"
        disabled: false
      conditions:
        host_tags: []
        service_labels: []
        host_labels: []
      value_raw: "{
        'htmllog': {
          'last_error_log': '.*',
          'last_log': '.*'
        },
        'robot_discovery_settings': [('.*', '2', '')],
        'robot_service_prefix': [('.*', 'E2E$SPACE-$SUITEID$SPACE-$SPACE')]
      }"
    state: present

- name: Create RobotMK service monitoring rule
  tribe29.checkmk.rule:
    server_url: "{{ cmk_server_url }}"
    site: "{{ cmk_site_name }}"
    automation_user: "automation"
    automation_secret: "{{ cmk_automation_pw }}"
    ruleset: "checkgroup_parameters:robotmk"
    rule:
      properties:
        comment: "Managed by ansible"
        description: "Monitoring RobotMK services"
        disabled: false
      conditions:
        host_tags: []
        service_labels: []
        host_labels: []
      value_raw: "{'includedate': 'yes'}"
    state: present

# When we add test cases to a suite, we want them activated automatically
- name: Create rule for automatic activation of dicovered test cases
  tribe29.checkmk.rule:
    server_url: "{{ cmk_server_url }}"
    site: "{{ cmk_site_name }}"
    automation_user: "automation"
    automation_secret: "{{ cmk_automation_pw }}"
    ruleset: "periodic_discovery"
    rule:
      properties:
        comment: "Managed by ansible"
        description: "Activate discovered RobotMK tests"
        disabled: false
      conditions:
        host_tags: []
        service_labels: []
        host_labels:
          - key: "robotmk"
            operator: "is"
            value: "yes"
      value_raw: "{
        'check_interval': 5.0,
        'inventory_rediscovery': {
          'activation': True,
          'excluded_time': [],
          'group_time': 900,
          'mode': 2,
          'service_filters': ('combined', {'service_whitelist': ['^E2E.*']})
        },
        'severity_new_host_label': 0,
        'severity_unmonitored': 0,
        'severity_vanished': 0
        }"
      location:
        folder: "/"
        position: "top"
    state: present

- name: Activate CheckMK changes
  tribe29.checkmk.activation:
    server_url: "{{ cmk_server_url }}"
    site: "{{ cmk_site_name }}"
    automation_user: "automation"
    automation_secret: "{{ cmk_automation_pw }}"
  register: activation

- name: Bake agents
  ansible.builtin.include_role:
    name: cmk-utils
    tasks_from: bake_and_sign_agents.yml
  when: activation is changed and cmk_agent_key_id is defined
